### PR TITLE
Movie card

### PR DESCRIPTION
**Pull request by jmg64**

### CODE REVIEW

**Comment by vanessacode** [comment]
Hello friends!
Please, can you modify 35 and 36 lines of HomeCardsVideo.js (delete movieSynopsis=),
thanks!

**Comment by srh1013** [comment]
Lines 35 and 36 of HomeCardsVideo.js (delete movieSynopsis=),
UPDATE ok

**Review by FabienGOYHEX — COMMENTED** [review]
Great Job

**Review by vanessacode — APPROVED** [review]
I'ts ok !

**Pull request merged**
