### PR TITLE
First version

### PR DESCRIPTION
**Pull request by jmg64**
Stable and functional work to merge with master

### CODE REVIEW

**Comment by vanessacode** [comment]
First functional version. The priority features are added, we are working to improve the search engine with new features. Soon a new version with an improved design will be ready.

**Review by vanessacode — APPROVED** [review]
The changes are right!

**Comment by srh1013** [comment]
Ça m’a l’air pas mal tout ça 👏🏽Well done!!

**Comment by Chojiu15** [comment]
Peut-on avoir un onClick sur le logo Movie Central afin de reload la page ? 
Peut-on sortir de la carte film en cliquant ailleurs que sur le close ?

**Review by Chojiu15 — APPROVED** [review]

**Pull request merged**
